<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<UseWindowsForms>true</UseWindowsForms>
		<ImplicitUsings>enable</ImplicitUsings>
		<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="EPPlus" Version="8.7.1" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\PluginsContracts\PluginsContracts.csproj" />
	</ItemGroup>

</Project>